/* auto-generated debug probe */
#if defined(BSWM_START_SEC_CODE)
#error "MEMMAP_DEBUG: BSWM_START_SEC_CODE"
#endif
#if defined(BSWM_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: BSWM_START_SEC_CONST_8BIT"
#endif
#if defined(BSWM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: BSWM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(BSWM_START_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: BSWM_START_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(BSWM_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: BSWM_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(BSWM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: BSWM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(BSWM_START_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: BSWM_START_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(BSWM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_CODE"
#endif
#if defined(BSWM_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_CONST_8BIT"
#endif
#if defined(BSWM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(BSWM_STOP_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(BSWM_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(BSWM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(BSWM_STOP_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: BSWM_STOP_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(CAN_START_SEC_CODE)
#error "MEMMAP_DEBUG: CAN_START_SEC_CODE"
#endif
#if defined(CAN_START_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: CAN_START_SEC_CONST_16BIT"
#endif
#if defined(CAN_START_SEC_CONST_32BIT)
#error "MEMMAP_DEBUG: CAN_START_SEC_CONST_32BIT"
#endif
#if defined(CAN_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CAN_START_SEC_CONST_8BIT"
#endif
#if defined(CAN_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CAN_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CAN_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CAN_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CAN_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CAN_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CAN_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_CODE"
#endif
#if defined(CAN_STOP_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_CONST_16BIT"
#endif
#if defined(CAN_STOP_SEC_CONST_32BIT)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_CONST_32BIT"
#endif
#if defined(CAN_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_CONST_8BIT"
#endif
#if defined(CAN_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CAN_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANIF_START_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: CANIF_START_SEC_APPL_CODE"
#endif
#if defined(CANIF_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANIF_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANIF_STOP_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: CANIF_STOP_SEC_APPL_CODE"
#endif
#if defined(CANIF_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANIF_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANNM_START_SEC_CODE)
#error "MEMMAP_DEBUG: CANNM_START_SEC_CODE"
#endif
#if defined(CANNM_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CANNM_START_SEC_CONST_8BIT"
#endif
#if defined(CANNM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANNM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANNM_START_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANNM_START_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(CANNM_START_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: CANNM_START_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(CANNM_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CANNM_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CANNM_START_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: CANNM_START_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(CANNM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_CODE"
#endif
#if defined(CANNM_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_CONST_8BIT"
#endif
#if defined(CANNM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANNM_STOP_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(CANNM_STOP_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(CANNM_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CANNM_STOP_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: CANNM_STOP_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(CANSM_START_SEC_CODE)
#error "MEMMAP_DEBUG: CANSM_START_SEC_CODE"
#endif
#if defined(CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANSM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: CANSM_STOP_SEC_CODE"
#endif
#if defined(CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANTP_START_SEC_CODE)
#error "MEMMAP_DEBUG: CANTP_START_SEC_CODE"
#endif
#if defined(CANTP_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CANTP_START_SEC_CONST_8BIT"
#endif
#if defined(CANTP_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANTP_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANTP_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CANTP_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANTP_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: CANTP_STOP_SEC_CODE"
#endif
#if defined(CANTP_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: CANTP_STOP_SEC_CONST_8BIT"
#endif
#if defined(CANTP_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANTP_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANTP_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: CANTP_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(CANXCP_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANXCP_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CANXCP_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: CANXCP_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(CDD_COM_START_SEC_CODE)
#error "MEMMAP_DEBUG: CDD_COM_START_SEC_CODE"
#endif
#if defined(CDD_COM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: CDD_COM_STOP_SEC_CODE"
#endif
#if defined(COM_START_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: COM_START_SEC_APPL_CODE"
#endif
#if defined(COM_START_SEC_CODE)
#error "MEMMAP_DEBUG: COM_START_SEC_CODE"
#endif
#if defined(COM_START_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_CONST_16BIT"
#endif
#if defined(COM_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_CONST_8BIT"
#endif
#if defined(COM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: COM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(COM_START_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(COM_START_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(COM_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(COM_START_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: COM_START_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(COM_STOP_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: COM_STOP_SEC_APPL_CODE"
#endif
#if defined(COM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: COM_STOP_SEC_CODE"
#endif
#if defined(COM_STOP_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_CONST_16BIT"
#endif
#if defined(COM_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_CONST_8BIT"
#endif
#if defined(COM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: COM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(COM_STOP_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(COM_STOP_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(COM_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(COM_STOP_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: COM_STOP_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(COMM_START_SEC_CODE)
#error "MEMMAP_DEBUG: COMM_START_SEC_CODE"
#endif
#if defined(COMM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: COMM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(COMM_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: COMM_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(COMM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: COMM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(COMM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: COMM_STOP_SEC_CODE"
#endif
#if defined(COMM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: COMM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(COMM_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: COMM_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DCM_START_SEC_CALLOUT_CODE)
#error "MEMMAP_DEBUG: DCM_START_SEC_CALLOUT_CODE"
#endif
#if defined(DCM_START_SEC_CODE)
#error "MEMMAP_DEBUG: DCM_START_SEC_CODE"
#endif
#if defined(DCM_START_SEC_CONST_16)
#error "MEMMAP_DEBUG: DCM_START_SEC_CONST_16"
#endif
#if defined(DCM_START_SEC_CONST_8)
#error "MEMMAP_DEBUG: DCM_START_SEC_CONST_8"
#endif
#if defined(DCM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: DCM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(DCM_START_SEC_VAR_NO_INIT_8)
#error "MEMMAP_DEBUG: DCM_START_SEC_VAR_NO_INIT_8"
#endif
#if defined(DCM_STOP_SEC_CALLOUT_CODE)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_CALLOUT_CODE"
#endif
#if defined(DCM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_CODE"
#endif
#if defined(DCM_STOP_SEC_CONST_16)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_CONST_16"
#endif
#if defined(DCM_STOP_SEC_CONST_8)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_CONST_8"
#endif
#if defined(DCM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(DCM_STOP_SEC_VAR_NO_INIT_8)
#error "MEMMAP_DEBUG: DCM_STOP_SEC_VAR_NO_INIT_8"
#endif
#if defined(DEM_START_SEC_0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_CODE)
#error "MEMMAP_DEBUG: DEM_START_SEC_CODE"
#endif
#if defined(DEM_START_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: DEM_START_SEC_CONST_16BIT"
#endif
#if defined(DEM_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: DEM_START_SEC_CONST_8BIT"
#endif
#if defined(DEM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE3_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE3_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE5_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_SYSTEMAPPLICATION_OSCORE_CORE5_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: DEM_START_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(DEM_START_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: DEM_START_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(DEM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_CODE"
#endif
#if defined(DEM_STOP_SEC_CONST_16BIT)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_CONST_16BIT"
#endif
#if defined(DEM_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_CONST_8BIT"
#endif
#if defined(DEM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE3_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE3_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE5_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_SYSTEMAPPLICATION_OSCORE_CORE5_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_VAR_NOINIT_16BIT"
#endif
#if defined(DEM_STOP_SEC_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_VAR_NOINIT_8BIT"
#endif
#if defined(DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#error "MEMMAP_DEBUG: DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED"
#endif
#if defined(DET_START_SEC_CODE)
#error "MEMMAP_DEBUG: DET_START_SEC_CODE"
#endif
#if defined(DET_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: DET_STOP_SEC_CODE"
#endif
#if defined(ECUM_START_SEC_CODE)
#error "MEMMAP_DEBUG: ECUM_START_SEC_CODE"
#endif
#if defined(ECUM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: ECUM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(ECUM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: ECUM_STOP_SEC_CODE"
#endif
#if defined(ECUM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: ECUM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(FEE_START_SEC_CODE)
#error "MEMMAP_DEBUG: FEE_START_SEC_CODE"
#endif
#if defined(FEE_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: FEE_STOP_SEC_CODE"
#endif
#if defined(FLS_17_PMU_START_SEC_CODE)
#error "MEMMAP_DEBUG: FLS_17_PMU_START_SEC_CODE"
#endif
#if defined(FLS_17_PMU_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: FLS_17_PMU_STOP_SEC_CODE"
#endif
#if defined(MEMIF_START_SEC_CODE)
#error "MEMMAP_DEBUG: MEMIF_START_SEC_CODE"
#endif
#if defined(MEMIF_START_SEC_CONST_32BIT)
#error "MEMMAP_DEBUG: MEMIF_START_SEC_CONST_32BIT"
#endif
#if defined(MEMIF_START_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: MEMIF_START_SEC_CONST_8BIT"
#endif
#if defined(MEMIF_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: MEMIF_STOP_SEC_CODE"
#endif
#if defined(MEMIF_STOP_SEC_CONST_32BIT)
#error "MEMMAP_DEBUG: MEMIF_STOP_SEC_CONST_32BIT"
#endif
#if defined(MEMIF_STOP_SEC_CONST_8BIT)
#error "MEMMAP_DEBUG: MEMIF_STOP_SEC_CONST_8BIT"
#endif
#if defined(NM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: NM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(NM_START_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NM_START_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(NM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: NM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(NM_STOP_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NM_STOP_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(NVM_START_SEC_CODE)
#error "MEMMAP_DEBUG: NVM_START_SEC_CODE"
#endif
#if defined(NVM_START_SEC_CONST_16)
#error "MEMMAP_DEBUG: NVM_START_SEC_CONST_16"
#endif
#if defined(NVM_START_SEC_CONST_8)
#error "MEMMAP_DEBUG: NVM_START_SEC_CONST_8"
#endif
#if defined(NVM_START_SEC_CONST_DESCRIPTOR_TABLE)
#error "MEMMAP_DEBUG: NVM_START_SEC_CONST_DESCRIPTOR_TABLE"
#endif
#if defined(NVM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(NVM_START_SEC_VAR_NOINIT_8)
#error "MEMMAP_DEBUG: NVM_START_SEC_VAR_NOINIT_8"
#endif
#if defined(NVM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED"
#endif
#if defined(NVM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_CODE"
#endif
#if defined(NVM_STOP_SEC_CONST_16)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_CONST_16"
#endif
#if defined(NVM_STOP_SEC_CONST_8)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_CONST_8"
#endif
#if defined(NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE"
#endif
#if defined(NVM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(NVM_STOP_SEC_VAR_NOINIT_8)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_VAR_NOINIT_8"
#endif
#if defined(NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_BARRIER_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_BARRIER_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CanIsr_0_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_CanIsr_0_CODE"
#endif
#if defined(OS_START_SEC_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_CODE"
#endif
#if defined(OS_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CORE0_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CORE0_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_CORESTATUS_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_CORESTATUS_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_Default_Appl_Init_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_Appl_Init_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_Appl_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_Appl_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_Background_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_Background_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_BSW_Async_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_BSW_Async_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_BSW_Sync_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_BSW_Sync_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_Init_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_Init_Task_CODE"
#endif
#if defined(OS_START_SEC_Default_RTE_Mode_switch_Task_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_Default_RTE_Mode_switch_Task_CODE"
#endif
#if defined(OS_START_SEC_ERRORHOOK_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_ERRORHOOK_CODE"
#endif
#if defined(OS_START_SEC_EXCVEC_CORE0_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_EXCVEC_CORE0_CODE"
#endif
#if defined(OS_START_SEC_EXCVEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_EXCVEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_FAST_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_FAST_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_FAST_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_FAST_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_FAST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_GLOBALSHARED_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_INTVEC_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_INTVEC_CODE"
#endif
#if defined(OS_START_SEC_INTVEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_INTVEC_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_INTVEC_CORE0_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_INTVEC_CORE0_CODE"
#endif
#if defined(OS_START_SEC_INTVEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_INTVEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_OS_COREINITHOOK_CODE)
#error "MEMMAP_DEBUG: OS_START_SEC_OS_COREINITHOOK_CODE"
#endif
#if defined(OS_START_SEC_PUBLIC_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_PUBLIC_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_DEFAULT_APPL_TASK_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_DEFAULT_APPL_TASK_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_DEFAULT_BSW_ASYNC_TASK_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_DEFAULT_BSW_ASYNC_TASK_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_ERROR_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_ERROR_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_INIT_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_INIT_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_ISR_CORE_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_ISR_CORE_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_KERNEL_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_KERNEL_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO6_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO6_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO7_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_STACK_OSCORE_CORE0_TASK_PRIO7_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_FAST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_CONST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_16BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_32BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_8BIT"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core3_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core3_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_SystemApplication_OsCore_Core5_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_SystemApplication_OsCore_Core5_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_START_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_START_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_BARRIER_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_BARRIER_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CanIsr_0_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CanIsr_0_CODE"
#endif
#if defined(OS_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CODE"
#endif
#if defined(OS_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CORE0_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CORE0_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_CORESTATUS_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_CORESTATUS_CORE0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_Default_Appl_Init_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_Appl_Init_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_Appl_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_Appl_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_Background_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_Background_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_BSW_Async_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_BSW_Async_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_BSW_Sync_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_BSW_Sync_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_Init_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_Init_Task_CODE"
#endif
#if defined(OS_STOP_SEC_Default_RTE_Mode_switch_Task_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_Default_RTE_Mode_switch_Task_CODE"
#endif
#if defined(OS_STOP_SEC_ERRORHOOK_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_ERRORHOOK_CODE"
#endif
#if defined(OS_STOP_SEC_EXCVEC_CORE0_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_EXCVEC_CORE0_CODE"
#endif
#if defined(OS_STOP_SEC_EXCVEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_EXCVEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_FAST_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_FAST_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_FAST_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_FAST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_FAST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_FAST_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_GLOBALSHARED_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_INTVEC_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_INTVEC_CODE"
#endif
#if defined(OS_STOP_SEC_INTVEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_INTVEC_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_INTVEC_CORE0_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_INTVEC_CORE0_CODE"
#endif
#if defined(OS_STOP_SEC_INTVEC_CORE0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_INTVEC_CORE0_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_OS_COREINITHOOK_CODE)
#error "MEMMAP_DEBUG: OS_STOP_SEC_OS_COREINITHOOK_CODE"
#endif
#if defined(OS_STOP_SEC_PUBLIC_CORE0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_PUBLIC_CORE0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_DEFAULT_APPL_TASK_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_DEFAULT_APPL_TASK_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_DEFAULT_BSW_ASYNC_TASK_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_DEFAULT_BSW_ASYNC_TASK_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_ERROR_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_ERROR_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_INIT_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_INIT_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_ISR_CORE_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_ISR_CORE_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_KERNEL_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_KERNEL_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO6_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO6_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO7_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_STACK_OSCORE_CORE0_TASK_PRIO7_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_FAST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_CONST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_FAST_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_16BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_16BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_32BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_32BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_8BIT"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_BOOLEAN)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_BOOLEAN"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core0_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core1_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core1_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core2_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core2_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core3_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core3_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core4_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core4_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_SystemApplication_OsCore_Core5_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_SystemApplication_OsCore_Core5_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(OS_STOP_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: OS_STOP_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED"
#endif
#if defined(PDUR_START_SEC_CODE)
#error "MEMMAP_DEBUG: PDUR_START_SEC_CODE"
#endif
#if defined(PDUR_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: PDUR_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(PDUR_START_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: PDUR_START_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(PDUR_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: PDUR_STOP_SEC_CODE"
#endif
#if defined(PDUR_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: PDUR_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(PDUR_STOP_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: PDUR_STOP_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(RTE_START_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_APPL_CODE"
#endif
#if defined(RTE_START_SEC_BSWM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_BSWM_APPL_CODE"
#endif
#if defined(RTE_START_SEC_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_CODE"
#endif
#if defined(RTE_START_SEC_COMM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_COMM_APPL_CODE"
#endif
#if defined(RTE_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(RTE_START_SEC_DCM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_DCM_APPL_CODE"
#endif
#if defined(RTE_START_SEC_DEMMASTER_0_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_DEMMASTER_0_APPL_CODE"
#endif
#if defined(RTE_START_SEC_DEMSATELLITE_0_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_DEMSATELLITE_0_APPL_CODE"
#endif
#if defined(RTE_START_SEC_DET_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_DET_APPL_CODE"
#endif
#if defined(RTE_START_SEC_ECUM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_ECUM_APPL_CODE"
#endif
#if defined(RTE_START_SEC_IOHWAB_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_IOHWAB_APPL_CODE"
#endif
#if defined(RTE_START_SEC_NVM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_NVM_APPL_CODE"
#endif
#if defined(RTE_START_SEC_OS_OSCORE_CORE0_SWC_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_OS_OSCORE_CORE0_SWC_APPL_CODE"
#endif
#if defined(RTE_START_SEC_STARTAPPLICATION_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_STARTAPPLICATION_APPL_CODE"
#endif
#if defined(RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED"
#endif
#if defined(RTE_START_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_START_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(RTE_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(RTE_START_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: RTE_START_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(RTE_START_SEC_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_START_SEC_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(RTE_START_SEC_WDGM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_START_SEC_WDGM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_BSWM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_BSWM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_CODE"
#endif
#if defined(RTE_STOP_SEC_COMM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_COMM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(RTE_STOP_SEC_DCM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_DCM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_DEMMASTER_0_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_DEMMASTER_0_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_DEMSATELLITE_0_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_DEMSATELLITE_0_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_DET_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_DET_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_ECUM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_ECUM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_IOHWAB_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_IOHWAB_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_NVM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_NVM_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_OS_OSCORE_CORE0_SWC_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_OS_OSCORE_CORE0_SWC_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_STARTAPPLICATION_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_STARTAPPLICATION_APPL_CODE"
#endif
#if defined(RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED"
#endif
#if defined(RTE_STOP_SEC_VAR_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_VAR_INIT_UNSPECIFIED"
#endif
#if defined(RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(RTE_STOP_SEC_VAR_ZERO_INIT_8BIT)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_VAR_ZERO_INIT_8BIT"
#endif
#if defined(RTE_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED"
#endif
#if defined(RTE_STOP_SEC_WDGM_APPL_CODE)
#error "MEMMAP_DEBUG: RTE_STOP_SEC_WDGM_APPL_CODE"
#endif
#if defined(SPI_START_SEC_CODE)
#error "MEMMAP_DEBUG: SPI_START_SEC_CODE"
#endif
#if defined(SPI_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: SPI_STOP_SEC_CODE"
#endif
#if defined(WDGIF_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGIF_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(WDGIF_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGIF_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(WDGM_GLOBAL_START_SEC_VAR_32BIT)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_START_SEC_VAR_32BIT"
#endif
#if defined(WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE"
#endif
#if defined(WDGM_GLOBAL_STOP_SEC_VAR_32BIT)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_STOP_SEC_VAR_32BIT"
#endif
#if defined(WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE"
#endif
#if defined(WDGM_SE0_START_SEC_VAR_NOINIT_32BIT_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_SE0_START_SEC_VAR_NOINIT_32BIT_CORE0_PRIVATE"
#endif
#if defined(WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE"
#endif
#if defined(WDGM_SE0_STOP_SEC_VAR_NOINIT_32BIT_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_SE0_STOP_SEC_VAR_NOINIT_32BIT_CORE0_PRIVATE"
#endif
#if defined(WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE)
#error "MEMMAP_DEBUG: WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED_CORE0_PRIVATE"
#endif
#if defined(WDGM_START_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: WDGM_START_SEC_APPL_CODE"
#endif
#if defined(WDGM_START_SEC_CODE)
#error "MEMMAP_DEBUG: WDGM_START_SEC_CODE"
#endif
#if defined(WDGM_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(WDGM_START_SEC_VAR_32BIT)
#error "MEMMAP_DEBUG: WDGM_START_SEC_VAR_32BIT"
#endif
#if defined(WDGM_START_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: WDGM_START_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(WDGM_START_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_START_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(WDGM_STOP_SEC_APPL_CODE)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_APPL_CODE"
#endif
#if defined(WDGM_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_CODE"
#endif
#if defined(WDGM_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(WDGM_STOP_SEC_VAR_32BIT)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_VAR_32BIT"
#endif
#if defined(WDGM_STOP_SEC_VAR_NOINIT_32BIT)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_VAR_NOINIT_32BIT"
#endif
#if defined(WDGM_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#error "MEMMAP_DEBUG: WDGM_STOP_SEC_VAR_NOINIT_UNSPECIFIED"
#endif
#if defined(XCP_START_SEC_CODE)
#error "MEMMAP_DEBUG: XCP_START_SEC_CODE"
#endif
#if defined(XCP_START_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: XCP_START_SEC_CONST_UNSPECIFIED"
#endif
#if defined(XCP_START_SEC_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: XCP_START_SEC_VAR_NOCACHE_NOINIT_32BIT"
#endif
#if defined(XCP_STOP_SEC_CODE)
#error "MEMMAP_DEBUG: XCP_STOP_SEC_CODE"
#endif
#if defined(XCP_STOP_SEC_CONST_UNSPECIFIED)
#error "MEMMAP_DEBUG: XCP_STOP_SEC_CONST_UNSPECIFIED"
#endif
#if defined(XCP_STOP_SEC_VAR_NOCACHE_NOINIT_32BIT)
#error "MEMMAP_DEBUG: XCP_STOP_SEC_VAR_NOCACHE_NOINIT_32BIT"
#endif
