/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  Rte_Hook.h
 *        Config:  TsiStandard.dpa
 *   ECU-Project:  MyECU
 *
 *     Generator:  MICROSAR RTE Generator Version 4.16.0
 *                 RTE Core Version 1.16.0
 *       License:  Unlimited license CBD1700982 for Shanghai Huizhong Automotive Manufacturing Co., Ltd.
 *
 *   Description:  Header file containing definitions for VFB tracing
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * Names of available VFB-Trace-Hooks
 **********************************************************************************************************************
 *
 * Not configured:
 *
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_Boot_Software_Identification_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Boot_Software_NumberOfModules_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF410_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF412_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DID_0xF413_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DataDiagnosticIdentifier_DID_DataDiagnosticIdentifier_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Data_DID_StartApplication_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_CanDriverVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_DiagnosticModuleVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_NmVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_OperatingSystemVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_DevelopmentData_TransportLayerVersion_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_EcuIdentification_Part_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadOnlyDID_DID_Data_GlobalTime_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_ReadWriteData_GlobalTime_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Example_WriteOnlyDID_DID_DataObject_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Example_WriteOnlyDID_DID_DataObject_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Hardware_Version_Hardware_Version_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_PeriodicDataSample_DataRecord_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_PeriodicDataSample_DataRecord_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_PeriodicDataSample_DataRecord_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_PeriodicDataSample_DataRecord_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_FreezeCurrentState_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ResetToDefault_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ResetToDefault_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ReturnControlToECU_Start
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Return
 *  Rte_CallHook_Dcm_DataServices_SampleIoControl_DID_Data_ShortTermAdjustment_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_SerialNumber_SerialNumber_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Spare_Part_Number_Spare_Part_Number_WriteData_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ConditionCheckRead_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ReadData_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_ReadData_Start
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_WriteData_Return
 *  Rte_CallHook_Dcm_DataServices_Vehicle_Identification_VIN_WriteData_Start
 *  Rte_CallHook_Dcm_RoutineServices_CheckProgrammingPreconditions_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_CheckProgrammingPreconditions_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_ForceBootMode_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_ForceBootMode_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_RequestResults_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_RequestResults_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_RequestResults_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_StartOnly_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Start_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Start_Start
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Stop_Return
 *  Rte_CallHook_Dcm_RoutineServices_SampleRoutineControl_Stop_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_CompareKey_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_CompareKey_Start
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_GetSeed_Return
 *  Rte_CallHook_Dcm_SecurityAccess_Level_3_GetSeed_Start
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_CompareKey_Return
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_CompareKey_Start
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_GetSeed_Return
 *  Rte_CallHook_Dcm_SecurityAccess_UnlockedL1_GetSeed_Start
 *  Rte_CallHook_DemMaster_0_CBInitEvt_DTC_0x000002_InitMonitorForEvent_Return
 *  Rte_CallHook_DemMaster_0_CBInitEvt_DTC_0x000002_InitMonitorForEvent_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_DID_0x1_DID_Data_GlobalTime_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_DemDataElementClass_StartApplication_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_DemDataElementClass_StartApplication_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x12_DID_Data_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x12_DID_Data_ReadData_Start
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x13_DID_Data_ReadData_Return
 *  Rte_CallHook_DemMaster_0_CBReadData_PID_0x13_DID_Data_ReadData_Start
 *  Rte_CallHook_NvM_NvM_RpNotifyJobEnd_NvMBlockDescriptor_StartApplication_JobFinished_Return
 *  Rte_CallHook_NvM_NvM_RpNotifyJobEnd_NvMBlockDescriptor_StartApplication_JobFinished_Start
 *  Rte_CallHook_StartApplication_EcuM_ShutdownTarget_SelectShutdownTarget_Return
 *  Rte_CallHook_StartApplication_EcuM_ShutdownTarget_SelectShutdownTarget_Start
 *  Rte_CallHook_StartApplication_PpDemOpCycle_PowerCycle_SetOperationCycleState_Return
 *  Rte_CallHook_StartApplication_PpDemOpCycle_PowerCycle_SetOperationCycleState_Start
 *  Rte_CallHook_StartApplication_PpDiagnosticMonitor_DEM_EVENT_StartApplication_SetEventStatus_Return
 *  Rte_CallHook_StartApplication_PpDiagnosticMonitor_DEM_EVENT_StartApplication_SetEventStatus_Start
 *  Rte_CallHook_StartApplication_PpNvmDataPort_ReadBlock_Return
 *  Rte_CallHook_StartApplication_PpNvmDataPort_ReadBlock_Start
 *  Rte_CallHook_StartApplication_PpNvmDataPort_WriteBlock_Return
 *  Rte_CallHook_StartApplication_PpNvmDataPort_WriteBlock_Start
 *  Rte_CallHook_StartApplication_UR_USR_CHNL_3c6d4e43_GetCurrentComMode_Return
 *  Rte_CallHook_StartApplication_UR_USR_CHNL_3c6d4e43_GetCurrentComMode_Start
 *  Rte_CallHook_StartApplication_UR_USR_CHNL_3c6d4e43_RequestComMode_Return
 *  Rte_CallHook_StartApplication_UR_USR_CHNL_3c6d4e43_RequestComMode_Start
 *  Rte_ComHookRx_Signal_Rx15bit_OnWrite_a1df81ad
 *  Rte_ComHookRx_Signal_Rx16bit_Cyclic_a691adb3
 *  Rte_ComHook_Signal_Rx15bit_OnWrite_a1df81ad_SigRx
 *  Rte_ComHook_Signal_Rx16bit_Cyclic_a691adb3_SigRx
 *  Rte_ComHook_Signal_Tx24bit_Cyclic_85bf3e37_SigTx
 *  Rte_ComHook_Signal_Tx32bit_OnWrite_b2cd4fc2_SigTx
 *  Rte_IrvReadHook_StartApplication_StartApplication_Cyclic250ms_IrvOccuranceCounterDid_Return
 *  Rte_IrvReadHook_StartApplication_StartApplication_Cyclic250ms_IrvOccuranceCounterDid_Start
 *  Rte_IrvReadHook_StartApplication_StartApplication_DIAG_DcmReadData_IrvOccuranceCounterDid_Return
 *  Rte_IrvReadHook_StartApplication_StartApplication_DIAG_DcmReadData_IrvOccuranceCounterDid_Start
 *  Rte_IrvReadHook_StartApplication_StartApplication_DIAG_DemReadData_IrvOccuranceCounterDid_Return
 *  Rte_IrvReadHook_StartApplication_StartApplication_DIAG_DemReadData_IrvOccuranceCounterDid_Start
 *  Rte_IrvReadHook_StartApplication_StartApplication_OnDataRec_RxData_IrvOccuranceCounterDid_Return
 *  Rte_IrvReadHook_StartApplication_StartApplication_OnDataRec_RxData_IrvOccuranceCounterDid_Start
 *  Rte_IrvWriteHook_StartApplication_StartApplication_DIAG_DcmWriteData_IrvOccuranceCounterDid_Return
 *  Rte_IrvWriteHook_StartApplication_StartApplication_DIAG_DcmWriteData_IrvOccuranceCounterDid_Start
 *  Rte_IrvWriteHook_StartApplication_StartApplication_OnDataRec_RxData_IrvOccuranceCounterDid_Return
 *  Rte_IrvWriteHook_StartApplication_StartApplication_OnDataRec_RxData_IrvOccuranceCounterDid_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Start
 *  Rte_ReadHook_StartApplication_PpRxCtrl_DeSignal_Rx16bit_Cyclic_a691adb3_Return
 *  Rte_ReadHook_StartApplication_PpRxCtrl_DeSignal_Rx16bit_Cyclic_a691adb3_Start
 *  Rte_ReadHook_StartApplication_PpRxData_DeSignal_Rx15bit_OnWrite_a1df81ad_Return
 *  Rte_ReadHook_StartApplication_PpRxData_DeSignal_Rx15bit_OnWrite_a1df81ad_Start
 *  Rte_Runnable_BswM_BswM_MainFunction_Return
 *  Rte_Runnable_BswM_BswM_MainFunction_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Start
 *  Rte_Runnable_ComM_GetCurrentComMode_Return
 *  Rte_Runnable_ComM_GetCurrentComMode_Start
 *  Rte_Runnable_ComM_GetInhibitionStatus_Return
 *  Rte_Runnable_ComM_GetInhibitionStatus_Start
 *  Rte_Runnable_ComM_GetMaxComMode_Return
 *  Rte_Runnable_ComM_GetMaxComMode_Start
 *  Rte_Runnable_ComM_GetRequestedComMode_Return
 *  Rte_Runnable_ComM_GetRequestedComMode_Start
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Return
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Start
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Return
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Start
 *  Rte_Runnable_ComM_PreventWakeUp_Return
 *  Rte_Runnable_ComM_PreventWakeUp_Start
 *  Rte_Runnable_ComM_ReadInhibitCounter_Return
 *  Rte_Runnable_ComM_ReadInhibitCounter_Start
 *  Rte_Runnable_ComM_RequestComMode_Return
 *  Rte_Runnable_ComM_RequestComMode_Start
 *  Rte_Runnable_ComM_ResetInhibitCounter_Return
 *  Rte_Runnable_ComM_ResetInhibitCounter_Start
 *  Rte_Runnable_ComM_SetECUGroupClassification_Return
 *  Rte_Runnable_ComM_SetECUGroupClassification_Start
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Return
 *  Rte_Runnable_Dcm_Dcm_MainFunction_Start
 *  Rte_Runnable_Dcm_GetActiveProtocol_Return
 *  Rte_Runnable_Dcm_GetActiveProtocol_Start
 *  Rte_Runnable_Dcm_GetRequestKind_Return
 *  Rte_Runnable_Dcm_GetRequestKind_Start
 *  Rte_Runnable_Dcm_GetSecurityLevel_Return
 *  Rte_Runnable_Dcm_GetSecurityLevel_Start
 *  Rte_Runnable_Dcm_GetSesCtrlType_Return
 *  Rte_Runnable_Dcm_GetSesCtrlType_Start
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Return
 *  Rte_Runnable_Dcm_ResetToDefaultSession_Start
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Return
 *  Rte_Runnable_Dcm_SetActiveDiagnostic_Start
 *  Rte_Runnable_DemMaster_0_ClearDTC_Return
 *  Rte_Runnable_DemMaster_0_ClearDTC_Start
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Return
 *  Rte_Runnable_DemMaster_0_Dem_MasterMainFunction_Start
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Return
 *  Rte_Runnable_DemMaster_0_GetDTCStatusAvailabilityMask_Start
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemMaster_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemMaster_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Return
 *  Rte_Runnable_DemMaster_0_GetEventFailed_Start
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemMaster_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Return
 *  Rte_Runnable_DemMaster_0_GetEventMemoryOverflow_Start
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventStatus_Start
 *  Rte_Runnable_DemMaster_0_GetEventTested_Return
 *  Rte_Runnable_DemMaster_0_GetEventTested_Start
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemMaster_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemMaster_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemMaster_0_GetIndicatorStatus_Return
 *  Rte_Runnable_DemMaster_0_GetIndicatorStatus_Start
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemMaster_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Return
 *  Rte_Runnable_DemMaster_0_GetNumberOfEventMemoryEntries_Start
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_GetOperationCycleState_Start
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Return
 *  Rte_Runnable_DemMaster_0_PostRunRequested_Start
 *  Rte_Runnable_DemMaster_0_SelectDTC_Return
 *  Rte_Runnable_DemMaster_0_SelectDTC_Start
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Return
 *  Rte_Runnable_DemMaster_0_SetOperationCycleState_Start
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Return
 *  Rte_Runnable_DemSatellite_0_Dem_SatelliteMainFunction_Start
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDTCOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Return
 *  Rte_Runnable_DemSatellite_0_GetDebouncingOfEvent_Start
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Return
 *  Rte_Runnable_DemSatellite_0_GetEventEnableCondition_Start
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventExtendedDataRecordEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFailed_Start
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Return
 *  Rte_Runnable_DemSatellite_0_GetEventFreezeFrameDataEx_Start
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Return
 *  Rte_Runnable_DemSatellite_0_GetEventTested_Start
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetEventUdsStatus_Start
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Return
 *  Rte_Runnable_DemSatellite_0_GetFaultDetectionCounter_Start
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Return
 *  Rte_Runnable_DemSatellite_0_GetMonitorStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventDebounceStatus_Start
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_ResetEventStatus_Start
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Return
 *  Rte_Runnable_DemSatellite_0_SetEventStatus_Start
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Return
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Start
 *  Rte_Runnable_EcuM_GetBootTarget_Return
 *  Rte_Runnable_EcuM_GetBootTarget_Start
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Start
 *  Rte_Runnable_EcuM_GetShutdownCause_Return
 *  Rte_Runnable_EcuM_GetShutdownCause_Start
 *  Rte_Runnable_EcuM_GetShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetShutdownTarget_Start
 *  Rte_Runnable_EcuM_SelectBootTarget_Return
 *  Rte_Runnable_EcuM_SelectBootTarget_Start
 *  Rte_Runnable_EcuM_SelectShutdownCause_Return
 *  Rte_Runnable_EcuM_SelectShutdownCause_Start
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Return
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Start
 *  Rte_Runnable_NvM_EraseBlock_Return
 *  Rte_Runnable_NvM_EraseBlock_Start
 *  Rte_Runnable_NvM_GetErrorStatus_Return
 *  Rte_Runnable_NvM_GetErrorStatus_Start
 *  Rte_Runnable_NvM_InvalidateNvBlock_Return
 *  Rte_Runnable_NvM_InvalidateNvBlock_Start
 *  Rte_Runnable_NvM_NvM_MainFunction_Return
 *  Rte_Runnable_NvM_NvM_MainFunction_Start
 *  Rte_Runnable_NvM_ReadBlock_Return
 *  Rte_Runnable_NvM_ReadBlock_Start
 *  Rte_Runnable_NvM_SetBlockProtection_Return
 *  Rte_Runnable_NvM_SetBlockProtection_Start
 *  Rte_Runnable_NvM_SetRamBlockStatus_Return
 *  Rte_Runnable_NvM_SetRamBlockStatus_Start
 *  Rte_Runnable_NvM_WriteBlock_Return
 *  Rte_Runnable_NvM_WriteBlock_Start
 *  Rte_Runnable_Os_OsCore_Core0_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore_Core0_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore_Core0_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore_Core0_swc_GetElapsedValue_Start
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic1000ms_Return
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic1000ms_Start
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic10ms_Return
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic10ms_Start
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic1ms_Return
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic1ms_Start
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic250ms_Return
 *  Rte_Runnable_StartApplication_StartApplication_Cyclic250ms_Start
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_ConditionCheckRead_Return
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_ConditionCheckRead_Start
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DcmReadData_Return
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DcmReadData_Start
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DcmWriteData_Return
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DcmWriteData_Start
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DemReadData_Return
 *  Rte_Runnable_StartApplication_StartApplication_DIAG_DemReadData_Start
 *  Rte_Runnable_StartApplication_StartApplication_Init_Return
 *  Rte_Runnable_StartApplication_StartApplication_Init_Start
 *  Rte_Runnable_StartApplication_StartApplication_MEM_JobFinished_Return
 *  Rte_Runnable_StartApplication_StartApplication_MEM_JobFinished_Start
 *  Rte_Runnable_StartApplication_StartApplication_OnDataRec_RxCtrl_Return
 *  Rte_Runnable_StartApplication_StartApplication_OnDataRec_RxCtrl_Start
 *  Rte_Runnable_StartApplication_StartApplication_OnDataRec_RxData_Return
 *  Rte_Runnable_StartApplication_StartApplication_OnDataRec_RxData_Start
 *  Rte_Runnable_WdgM_CheckpointReached_Return
 *  Rte_Runnable_WdgM_CheckpointReached_Start
 *  Rte_Runnable_WdgM_GetFirstExpiredSEID_Return
 *  Rte_Runnable_WdgM_GetFirstExpiredSEID_Start
 *  Rte_Runnable_WdgM_GetGlobalStatus_Return
 *  Rte_Runnable_WdgM_GetGlobalStatus_Start
 *  Rte_Runnable_WdgM_GetLocalStatus_Return
 *  Rte_Runnable_WdgM_GetLocalStatus_Start
 *  Rte_Runnable_WdgM_GetMode_Return
 *  Rte_Runnable_WdgM_GetMode_Start
 *  Rte_Runnable_WdgM_PerformReset_Return
 *  Rte_Runnable_WdgM_PerformReset_Start
 *  Rte_Runnable_WdgM_SetMode_Return
 *  Rte_Runnable_WdgM_SetMode_Start
 *  Rte_Runnable_WdgM_WdgM_MainFunction_Return
 *  Rte_Runnable_WdgM_WdgM_MainFunction_Start
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchAckHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Return
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Start
 *  Rte_SwitchHook_Dcm_DcmCommunicationControl_ComMConf_ComMChannel_CAN_f26020e5_DcmCommunicationControl_ComMConf_ComMChannel_CAN_f26020e5_Return
 *  Rte_SwitchHook_Dcm_DcmCommunicationControl_ComMConf_ComMChannel_CAN_f26020e5_DcmCommunicationControl_ComMConf_ComMChannel_CAN_f26020e5_Start
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Return
 *  Rte_SwitchHook_Dcm_DcmControlDtcSetting_DcmControlDtcSetting_Start
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Return
 *  Rte_SwitchHook_Dcm_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl_Start
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Return
 *  Rte_SwitchHook_Dcm_DcmEcuReset_DcmEcuReset_Start
 *  Rte_Task_Activate
 *  Rte_Task_Dispatch
 *  Rte_Task_SetEvent
 *  Rte_Task_WaitEvent
 *  Rte_Task_WaitEventRet
 *  Rte_WriteHook_BswM_Provide_BswMRteModeRequestPort_requestedMode_Return
 *  Rte_WriteHook_BswM_Provide_BswMRteModeRequestPort_requestedMode_Start
 *  Rte_WriteHook_StartApplication_PpTxCtrl_DeSignal_Tx32bit_OnWrite_b2cd4fc2_Return
 *  Rte_WriteHook_StartApplication_PpTxCtrl_DeSignal_Tx32bit_OnWrite_b2cd4fc2_Start
 *  Rte_WriteHook_StartApplication_PpTxData_DeSignal_Tx24bit_Cyclic_85bf3e37_Return
 *  Rte_WriteHook_StartApplication_PpTxData_DeSignal_Tx24bit_Cyclic_85bf3e37_Start
 *  SchM_EnterHook_Adc_DisableHwTrig_Return
 *  SchM_EnterHook_Adc_DisableHwTrig_Start
 *  SchM_EnterHook_Adc_EnableHwTrig_Return
 *  SchM_EnterHook_Adc_EnableHwTrig_Start
 *  SchM_EnterHook_Adc_GetGrpStatus_Return
 *  SchM_EnterHook_Adc_GetGrpStatus_Start
 *  SchM_EnterHook_Adc_GetStreamLastPtr_Return
 *  SchM_EnterHook_Adc_GetStreamLastPtr_Start
 *  SchM_EnterHook_Adc_PopQueue_Return
 *  SchM_EnterHook_Adc_PopQueue_Start
 *  SchM_EnterHook_Adc_PushQueue_Return
 *  SchM_EnterHook_Adc_PushQueue_Start
 *  SchM_EnterHook_Adc_ReadGroup_Return
 *  SchM_EnterHook_Adc_ReadGroup_Start
 *  SchM_EnterHook_Adc_ScheduleNext_Return
 *  SchM_EnterHook_Adc_ScheduleNext_Start
 *  SchM_EnterHook_Adc_ScheduleStart_Return
 *  SchM_EnterHook_Adc_ScheduleStart_Start
 *  SchM_EnterHook_Adc_ScheduleStop_Return
 *  SchM_EnterHook_Adc_ScheduleStop_Start
 *  SchM_EnterHook_Adc_StartGroup_Return
 *  SchM_EnterHook_Adc_StartGroup_Start
 *  SchM_EnterHook_Adc_StopGroup_Return
 *  SchM_EnterHook_Adc_StopGroup_Start
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanNm_CANNM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Fls_17_Pmu_Erase_Return
 *  SchM_EnterHook_Fls_17_Pmu_Erase_Start
 *  SchM_EnterHook_Fls_17_Pmu_Init_Return
 *  SchM_EnterHook_Fls_17_Pmu_Init_Start
 *  SchM_EnterHook_Fls_17_Pmu_Main_Return
 *  SchM_EnterHook_Fls_17_Pmu_Main_Start
 *  SchM_EnterHook_Fls_17_Pmu_ResumeErase_Return
 *  SchM_EnterHook_Fls_17_Pmu_ResumeErase_Start
 *  SchM_EnterHook_Fls_17_Pmu_Write_Return
 *  SchM_EnterHook_Fls_17_Pmu_Write_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_Ccu6IenUpdate_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_Ccu6IenUpdate_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_CcuInterruptHandle_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_CcuInterruptHandle_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_CcuVariableupdate_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_CcuVariableupdate_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_EnableNotification_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_EnableNotification_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_EnableWakeup_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_EnableWakeup_Start
 *  SchM_EnterHook_Icu_17_GtmCcu6_ResetEdgeCount_Return
 *  SchM_EnterHook_Icu_17_GtmCcu6_ResetEdgeCount_Start
 *  SchM_EnterHook_IoHwAb_IOHWAB_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_IoHwAb_IOHWAB_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Nm_NM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Nm_NM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Nm_NM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Nm_NM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_NvM_NVM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_NvM_NVM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Spi_AsyncTransmit_Return
 *  SchM_EnterHook_Spi_AsyncTransmit_Start
 *  SchM_EnterHook_Spi_Cancel_Return
 *  SchM_EnterHook_Spi_Cancel_Start
 *  SchM_EnterHook_Spi_DeInit_Return
 *  SchM_EnterHook_Spi_DeInit_Start
 *  SchM_EnterHook_Spi_GetSequenceResult_Return
 *  SchM_EnterHook_Spi_GetSequenceResult_Start
 *  SchM_EnterHook_Spi_Init_Return
 *  SchM_EnterHook_Spi_Init_Start
 *  SchM_EnterHook_Spi_SyncTransmit_Return
 *  SchM_EnterHook_Spi_SyncTransmit_Start
 *  SchM_EnterHook_Spi_WriteIB_Return
 *  SchM_EnterHook_Spi_WriteIB_Start
 *  SchM_EnterHook_WdgM_WDGM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_WdgM_WDGM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Wdg_17_Scu_ChangeMode_Return
 *  SchM_EnterHook_Wdg_17_Scu_ChangeMode_Start
 *  SchM_EnterHook_Wdg_17_Scu_SafetyInit_Return
 *  SchM_EnterHook_Wdg_17_Scu_SafetyInit_Start
 *  SchM_EnterHook_Wdg_17_Scu_SafetyOffMode_Return
 *  SchM_EnterHook_Wdg_17_Scu_SafetyOffMode_Start
 *  SchM_EnterHook_Wdg_17_Scu_SafetyTrigger_Return
 *  SchM_EnterHook_Wdg_17_Scu_SafetyTrigger_Start
 *  SchM_EnterHook_Wdg_17_Scu_TimerHandling_Return
 *  SchM_EnterHook_Wdg_17_Scu_TimerHandling_Start
 *  SchM_EnterHook_Wdg_17_Scu_Trigger_Return
 *  SchM_EnterHook_Wdg_17_Scu_Trigger_Start
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Adc_DisableHwTrig_Return
 *  SchM_ExitHook_Adc_DisableHwTrig_Start
 *  SchM_ExitHook_Adc_EnableHwTrig_Return
 *  SchM_ExitHook_Adc_EnableHwTrig_Start
 *  SchM_ExitHook_Adc_GetGrpStatus_Return
 *  SchM_ExitHook_Adc_GetGrpStatus_Start
 *  SchM_ExitHook_Adc_GetStreamLastPtr_Return
 *  SchM_ExitHook_Adc_GetStreamLastPtr_Start
 *  SchM_ExitHook_Adc_PopQueue_Return
 *  SchM_ExitHook_Adc_PopQueue_Start
 *  SchM_ExitHook_Adc_PushQueue_Return
 *  SchM_ExitHook_Adc_PushQueue_Start
 *  SchM_ExitHook_Adc_ReadGroup_Return
 *  SchM_ExitHook_Adc_ReadGroup_Start
 *  SchM_ExitHook_Adc_ScheduleNext_Return
 *  SchM_ExitHook_Adc_ScheduleNext_Start
 *  SchM_ExitHook_Adc_ScheduleStart_Return
 *  SchM_ExitHook_Adc_ScheduleStart_Start
 *  SchM_ExitHook_Adc_ScheduleStop_Return
 *  SchM_ExitHook_Adc_ScheduleStop_Start
 *  SchM_ExitHook_Adc_StartGroup_Return
 *  SchM_ExitHook_Adc_StartGroup_Start
 *  SchM_ExitHook_Adc_StopGroup_Return
 *  SchM_ExitHook_Adc_StopGroup_Start
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanNm_CANNM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanTp_CANTP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dcm_DCM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Dem_DEM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Fls_17_Pmu_Erase_Return
 *  SchM_ExitHook_Fls_17_Pmu_Erase_Start
 *  SchM_ExitHook_Fls_17_Pmu_Init_Return
 *  SchM_ExitHook_Fls_17_Pmu_Init_Start
 *  SchM_ExitHook_Fls_17_Pmu_Main_Return
 *  SchM_ExitHook_Fls_17_Pmu_Main_Start
 *  SchM_ExitHook_Fls_17_Pmu_ResumeErase_Return
 *  SchM_ExitHook_Fls_17_Pmu_ResumeErase_Start
 *  SchM_ExitHook_Fls_17_Pmu_Write_Return
 *  SchM_ExitHook_Fls_17_Pmu_Write_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_Ccu6IenUpdate_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_Ccu6IenUpdate_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_CcuInterruptHandle_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_CcuInterruptHandle_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_CcuVariableupdate_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_CcuVariableupdate_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_EnableNotification_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_EnableNotification_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_EnableWakeup_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_EnableWakeup_Start
 *  SchM_ExitHook_Icu_17_GtmCcu6_ResetEdgeCount_Return
 *  SchM_ExitHook_Icu_17_GtmCcu6_ResetEdgeCount_Start
 *  SchM_ExitHook_IoHwAb_IOHWAB_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_IoHwAb_IOHWAB_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Nm_NM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Nm_NM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Nm_NM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Nm_NM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_NvM_NVM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_NvM_NVM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Spi_AsyncTransmit_Return
 *  SchM_ExitHook_Spi_AsyncTransmit_Start
 *  SchM_ExitHook_Spi_Cancel_Return
 *  SchM_ExitHook_Spi_Cancel_Start
 *  SchM_ExitHook_Spi_DeInit_Return
 *  SchM_ExitHook_Spi_DeInit_Start
 *  SchM_ExitHook_Spi_GetSequenceResult_Return
 *  SchM_ExitHook_Spi_GetSequenceResult_Start
 *  SchM_ExitHook_Spi_Init_Return
 *  SchM_ExitHook_Spi_Init_Start
 *  SchM_ExitHook_Spi_SyncTransmit_Return
 *  SchM_ExitHook_Spi_SyncTransmit_Start
 *  SchM_ExitHook_Spi_WriteIB_Return
 *  SchM_ExitHook_Spi_WriteIB_Start
 *  SchM_ExitHook_WdgM_WDGM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_WdgM_WDGM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Wdg_17_Scu_ChangeMode_Return
 *  SchM_ExitHook_Wdg_17_Scu_ChangeMode_Start
 *  SchM_ExitHook_Wdg_17_Scu_SafetyInit_Return
 *  SchM_ExitHook_Wdg_17_Scu_SafetyInit_Start
 *  SchM_ExitHook_Wdg_17_Scu_SafetyOffMode_Return
 *  SchM_ExitHook_Wdg_17_Scu_SafetyOffMode_Start
 *  SchM_ExitHook_Wdg_17_Scu_SafetyTrigger_Return
 *  SchM_ExitHook_Wdg_17_Scu_SafetyTrigger_Start
 *  SchM_ExitHook_Wdg_17_Scu_TimerHandling_Return
 *  SchM_ExitHook_Wdg_17_Scu_TimerHandling_Start
 *  SchM_ExitHook_Wdg_17_Scu_Trigger_Return
 *  SchM_ExitHook_Wdg_17_Scu_Trigger_Start
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_Schedulable_BswM_BswM_MainFunction_Return
 *  SchM_Schedulable_BswM_BswM_MainFunction_Start
 *  SchM_Schedulable_CanNm_CanNm_MainFunction_Return
 *  SchM_Schedulable_CanNm_CanNm_MainFunction_Start
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Return
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Start
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Return
 *  SchM_Schedulable_CanTp_CanTp_MainFunction_Start
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Return
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Start
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Start
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Start
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Return
 *  SchM_Schedulable_Dcm_Dcm_MainFunction_Start
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_MasterMainFunction_Start
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Return
 *  SchM_Schedulable_Dem_Dem_SatelliteMainFunction_Start
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Return
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Start
 *  SchM_Schedulable_Fee_Fee_MainFunction_Return
 *  SchM_Schedulable_Fee_Fee_MainFunction_Start
 *  SchM_Schedulable_Fls_17_Pmu_Fls_17_Pmu_MainFunction_Return
 *  SchM_Schedulable_Fls_17_Pmu_Fls_17_Pmu_MainFunction_Start
 *  SchM_Schedulable_NvM_NvM_MainFunction_Return
 *  SchM_Schedulable_NvM_NvM_MainFunction_Start
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Return
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Start
 *  SchM_Schedulable_WdgM_WdgM_MainFunction_Return
 *  SchM_Schedulable_WdgM_WdgM_MainFunction_Start
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Start
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Start
 *
 *********************************************************************************************************************/

/* double include prevention */
#ifndef _RTE_HOOK_H
# define _RTE_HOOK_H

# include "Os.h" /* PRQA S 0828, 0883 */ /* MD_MSR_1.1_828, MD_Rte_Os */

# include "Rte_Type.h"
# include "Rte_Cfg.h"

# ifndef RTE_VFB_TRACE
#  define RTE_VFB_TRACE (0)
# endif

#endif /* _RTE_HOOK_H */

/**********************************************************************************************************************
 MISRA 2004 violations and justifications
 *********************************************************************************************************************/

/* module specific MISRA deviations:
   MD_Rte_Os:
     Reason:     This justification is used as summary justification for all deviations caused by the MICROSAR OS
                 which is for testing of the RTE. Those deviations are no issues in the RTE code.
     Risk:       No functional risk.
     Prevention: Not required.

*/
