#######################################################################################################################
# File Name  : Makefile.config                                                                                        #
# Description: This makefile contains the target specific project settings (will be included by Makefile)             #
# Project    : Vector Basic Runtime System                                                                            #
# Module     : BrsHw for Platform Infineon Aurix                                                                      #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# COPYRIGHT                                                                                                           #
#---------------------------------------------------------------------------------------------------------------------#
# Copyright (c) 2017 by Vector Informatik GmbH.                                                  All rights reserved. #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# AUTHOR IDENTITY                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# Name                          Initials      Company                                                                 #
# ----------------------------  ------------  ------------------------------------------------------------------------#
# Benjamin Walter               visbwa        Vector Informatik GmbH                                                  #
# Timo Müller                   vistir        Vector Informatik GmbH                                                  #
# Jens Haerer                   visjhr        Vector Informatik GmbH                                                  #
# Nika Hamidi                   visnhi        Vector Informatik GmbH                                                  #
# Sascha Mauser                 vismaa        Vector Informatik GmbH                                                  #
#---------------------------------------------------------------------------------------------------------------------#
# REVISION HISTORY                                                                                                    #
#---------------------------------------------------------------------------------------------------------------------#
# Version   Date        Author  Description                                                                           #
# --------  ----------  ------  --------------------------------------------------------------------------------------#
# 01.00.00  2014-09-08  visbwa  First Version (derived from zBrs_Tricore 2.01.24)                                     #
# 01.00.01  2014-10-31  vistir  Added COREx_START_IMMEDAIATE                                                          #
# 01.00.02  2015-02-24  visbwa  Added EvalBoard TRIBOARD                                                              #
# 01.00.03  2015-04-30  visjhr  Addded support for TriBoards: TC2x2, TC2x3, TC2x4, TC2x5, TC2x7                       #
# 01.00.04  2015-09-02  vismin/visvnn Added support for TriBoard TC2x8                                                #
# 01.00.05  2016-05-24  visbwa  Introduced OSGEN7 support, added TRIBOARD_TC2x9                                       #
# 01.01.00  2016-06-08  visbwa  Adapted complete file header structure for zBrs_Template@root[2.00.01]                #
# 01.01.01  2016-09-01  visnhi  Added USER_LINKER_COMMAND_FILE for Gen7-OS with GNU Compiler                          #
# 01.01.02  2016-09-26  visbwa  Encapsuled USER_LINKER_COMMAND_FILE for Gen7-OS for GNU Compiler with Compiler switch #
# 01.01.03  2016-12-02  vismaa  Added support for HSR_365                                                             #
# 01.01.04  2016-12-20  visbwa  Fixed encapsulation of USER_LINKER_COMMAND_FILE                                       #
# 01.01.05  2017-01-09  visbwa  Moved USER_LINKER_COMMAND_FILE for OsGen7 and GNU to Makefile                         #
# 01.01.06  2017-11-29  visbwa  Added support for MAIN_OSC_CLK = 40MHz                                                #
#######################################################################################################################

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Derivative (see BrsHw_DerivativeList.h for supported ones)
# This is used for ROM/RAM mapping, compiler switches, etc...
#------------------------------------------------------------------------------
DERIVATIVE = TC23X

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select clock frequency of main oscillator (MHz)
# Supported frequencies are 16, 20 and 40 MHz
#------------------------------------------------------------------------------
MAIN_OSC_CLK = 20

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select BRS time base clock (MHz).
# PLL will always be set to 200MHz, but this frequency is the 
# CPU clock of the cores.
# Possible values are:  Derivative specific
#------------------------------------------------------------------------------
TIMEBASE_CLOCK = 120

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select EVA board, possible values are:
#           TRIBOARD_TC2x2
#           TRIBOARD_TC2x3
#           TRIBOARD_TC2x4
#           TRIBOARD_TC2x5
#           TRIBOARD_TC2x7
#           TRIBOARD_TC2x8
#           TRIBOARD_TC2x9
#           CUSTOMER_HARDWARE
#           VEBN01263 - TC222 (Toggle Port 11 Pin 11)
#           HSR_365 - USG5 mainBoard with TC299 daughterboard
#------------------------------------------------------------------------------
EVA_BOARD = TRIBOARD_TC2x4

#------------------------- Can be filled out ----------------------------------
# Select the type of used OS
# possible values are: BRS      Timer/IRQ generated by BRS (Default)
#                      OS       Timer/IRQ generated by OS
#                      SAFECTX  SafeContext ASR OS used
#                      OSGEN7   Os_CoreGen7 based MICROSAR OS
#
# Please note: If the parameter is set to SafeCtx, make sure the
#              GHS linker option "--preprocess_linker_directive" is used,
#              otherwise the includes in the linker script won't work!
#------------------------------------------------------------------------------
OS_USECASE = OSGEN7

#------------------------------------------------------------------------------
#------------------------- Can be filled out (for Tasking compiler) -----------
# Configure here, which Cores should be started immediately by StartUpCode.
# Core0 is always started. Default values for Core1 and Core2 are "0".
# Possible values are:
#           0 = Do not start Core immediately within StartUpCode
#                 (can be done later on, e.g. by MultiCore-OS)
#           1 = Start Core immediately within StartUpCode
#------------------------------------------------------------------------------
CORE1_START_IMMEDIATE = 0
CORE2_START_IMMEDIATE = 0
